---
version: '3'

env:
  BUILD_TYPE: '{{.BUILD_TYPE | default "debug"}}'
  BUILD_DIR: 'build'

dotenv: [ '.env' ]

tasks:
  setup:internal:
    internal: true
    cmds:
      - meson setup {{.BUILD_DIR}} --buildtype={{.BUILD_TYPE}} --cross-file cross_file/kernel-{{.ARCH}}-{{.COMPILER}}.cross_file {{.CLI_ARGS}}
  setup:x86_64:clang-18:
    cmds:
      - task: setup:internal
        vars:
          ARCH: x86_64
          COMPILER: clang-18
  setup:wipe:
    cmds:
      - rm -r {{.BUILD_DIR}}

  compile:kernel:
    cmds:
      - meson compile -C {{.BUILD_DIR}} kernel.elf

  build:iso:
    cmds:
      - meson compile -C {{.BUILD_DIR}} iso

  qemu:debug-with-bios:
    cmds:
      - meson compile -C {{.BUILD_DIR}} qemu_debug_with_bios
  qemu:debug-with-uefi:
    cmds:
      - meson compile -C {{.BUILD_DIR}} qemu_debug_with_uefi
  qemu:run-with-bios:
    cmds:
      - meson compile -C {{.BUILD_DIR}} qemu_run_with_bios
  qemu:run-with-uefi:
    cmds:
      - meson compile -C {{.BUILD_DIR}} qemu_run_with_uefi
