---
version: '3'

env:
  BUILD_TYPE: '{{.BUILD_TYPE | default "debug"}}'
  BUILD_DIR: 'build'

dotenv: [ '.env' ]

tasks:
  setup:x86_64:
    cmds:
      - meson setup {{.BUILD_DIR}} --cross-file cross_file/meson_kernel_x86_64.cross_file -Dbuildtype={{.BUILD_TYPE}} {{.CLI_ARGS}}
  setup:x86_64-debug:
    cmds:
      - meson setup {{.BUILD_DIR}} --cross-file cross_file/meson_kernel_x86_64.cross_file -Dgdb=true -Dkernel_ubsan=true -Dbuildtype={{.BUILD_TYPE}} {{.CLI_ARGS}}
  
  build:kernel:
    cmds:
      - meson compile -C {{.BUILD_DIR}} kernel.elf
  build:iso:
    cmds:
      - meson compile -C {{.BUILD_DIR}} iso

  qemu:debug-with-bios:
    cmds:
      - meson compile -C {{.BUILD_DIR}} qemu_debug_with_bios
  qemu:debug-with-uefi:
    cmds:
      - meson compile -C {{.BUILD_DIR}} qemu_debug_with_uefi
  qemu:run-with-bios:
    cmds:
      - meson compile -C {{.BUILD_DIR}} qemu_run_with_bios
  qemu:run-with-uefi:
    cmds:
      - meson compile -C {{.BUILD_DIR}} qemu_run_with_uefi
