---
name: CI

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build-iso:
    name: Build Kernel
    runs-on: ubuntu-22.04
    container: 3uclid3/nos-buildenv:latest

    strategy:
      fail-fast: false
      matrix:
        build-type: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build
        run: |
            task build:setup BUILD_TYPE=${{ matrix.build-type }};

      - name: Compile kernel
        run: |
          task kernel:compile

      - name: Build ISO
        run: |
          task iso:build
